using System.Collections.Generic;

namespace KuaiDiHelper.Utils
{
    public class Company
    {
        public static Dictionary<string, string> getCompanyDictionary()
        {
            return new Dictionary<string, string> {
                {
                    "shentong",
                    "申通快递"
                },
                {
                    "ems",
                    "EMS"
                },
                {
                    "shunfeng",
                    "顺丰速运"
                },
                {
                    "yunda",
                    "韵达快递"
                },
                {
                    "yuantong",
                    "圆通速递"
                },
                {
                    "zhongtong",
                    "中通快递"
                },
                {
                    "huitongkuaidi",
                    "百世汇通"
                },
                {
                    "tiantian",
                    "天天快递"
                },
                {
                    "zhaijisong",
                    "宅急送"
                },
                {
                    "xinhongyukuaidi",
                    "鑫飞鸿"
                },
                {
                    "cces",
                    "CCES/国通快递"
                },
                {
                    "quanyikuaidi",
                    "全一快递"
                },
                {
                    "biaojikuaidi",
                    "彪记快递"
                },
                {
                    "xingchengjibian",
                    "星晨急便"
                },
                {
                    "yafengsudi",
                    "亚风速递"
                },
                {
                    "yuanweifeng",
                    "源伟丰"
                },
                {
                    "quanritongkuaidi",
                    "全日通"
                },
                {
                    "anxindakuaixi",
                    "安信达"
                },
                {
                    "minghangkuaidi",
                    "民航快递"
                },
                {
                    "fenghuangkuaidi",
                    "凤凰快递"
                },
                {
                    "jinguangsudikuaijian",
                    "京广速递"
                },
                {
                    "peisihuoyunkuaidi",
                    "配思货运"
                },
                {
                    "ztky",
                    "中铁物流"
                },
                {
                    "ups",
                    "UPS"
                },
                {
                    "fedex",
                    "FedEx-国际件"
                },
                {
                    "tnt",
                    "TNT"
                },
                {
                    "dhl",
                    "DHL-中国件"
                },
                {
                    "aae",
                    "AAE-中国件"
                },
                {
                    "datianwuliu",
                    "大田物流"
                },
                {
                    "debangwuliu",
                    "德邦物流"
                },
                {
                    "xinbangwuliu",
                    "新邦物流"
                },
                {
                    "longbanwuliu",
                    "龙邦速递"
                },
                {
                    "yibangwuliu",
                    "一邦速递"
                },
                {
                    "suer",
                    "速尔快递"
                },
                {
                    "lianhaowuliu",
                    "联昊通"
                },
                {
                    "guangdongyouzhengwuliu",
                    "广东邮政"
                },
                {
                    "zhongyouwuliu",
                    "中邮物流"
                },
                {
                    "tiandihuayu",
                    "天地华宇"
                },
                {
                    "shenghuiwuliu",
                    "盛辉物流"
                },
                {
                    "changyuwuliu",
                    "长宇物流"
                },
                {
                    "feikangda",
                    "飞康达"
                },
                {
                    "yuanzhijiecheng",
                    "元智捷诚"
                },
                {
                    "youzhengguonei",
                    "邮政包裹/平邮"
                },
                {
                    "youzhengguoji",
                    "国际包裹"
                },
                {
                    "wanjiawuliu",
                    "万家物流"
                },
                {
                    "yuanchengwuliu",
                    "远成物流"
                },
                {
                    "xinfengwuliu",
                    "信丰物流"
                },
                {
                    "wenjiesudi",
                    "文捷航空"
                },
                {
                    "quanchenkuaidi",
                    "全晨快递"
                },
                {
                    "jiayiwuliu",
                    "佳怡物流"
                },
                {
                    "youshuwuliu",
                    "优速物流"
                },
                {
                    "kuaijiesudi",
                    "快捷速递"
                },
                {
                    "dsukuaidi",
                    "D速快递"
                },
                {
                    "quanjitong",
                    "全际通"
                },
                {
                    "ganzhongnengda",
                    "能达速递"
                },
                {
                    "anjiekuaidi",
                    "青岛安捷快递"
                },
                {
                    "yuefengwuliu",
                    "越丰物流"
                },
                {
                    "dpex",
                    "DPEX"
                },
                {
                    "jixianda",
                    "急先达"
                },
                {
                    "baifudongfang",
                    "百福东方"
                },
                {
                    "bht",
                    "BHT"
                },
                {
                    "wuyuansudi",
                    "伍圆速递"
                },
                {
                    "lanbiaokuaidi",
                    "蓝镖快递"
                },
                {
                    "coe",
                    "COE"
                },
                {
                    "nanjing",
                    "南京100"
                },
                {
                    "hengluwuliu",
                    "恒路物流"
                },
                {
                    "jindawuliu",
                    "金大物流"
                },
                {
                    "huaxialongwuliu",
                    "华夏龙"
                },
                {
                    "yuntongkuaidi",
                    "运通中港"
                },
                {
                    "jiajiwuliu",
                    "佳吉快运"
                },
                {
                    "shengfengwuliu",
                    "盛丰物流"
                },
                {
                    "yuananda",
                    "源安达"
                },
                {
                    "jiayunmeiwuliu",
                    "加运美"
                },
                {
                    "wanxiangwuliu",
                    "万象物流"
                },
                {
                    "hongpinwuliu",
                    "宏品物流"
                },
                {
                    "gls",
                    "GLS"
                },
                {
                    "shangda",
                    "上大物流"
                },
                {
                    "zhongtiewuliu",
                    "中铁快运"
                },
                {
                    "yuanfeihangwuliu",
                    "原飞航"
                },
                {
                    "haiwaihuanqiu",
                    "海外环球"
                },
                {
                    "santaisudi",
                    "三态速递"
                },
                {
                    "jinyuekuaidi",
                    "晋越快递"
                },
                {
                    "lianbangkuaidi",
                    "联邦快递"
                },
                {
                    "feikuaida",
                    "飞快达"
                },
                {
                    "quanfengkuaidi",
                    "全峰快递"
                },
                {
                    "rufengda",
                    "如风达"
                },
                {
                    "lejiedi",
                    "乐捷递"
                },
                {
                    "zhongxinda",
                    "忠信达"
                },
                {
                    "zhimakaimen",
                    "芝麻开门"
                },
                {
                    "saiaodi",
                    "赛澳递"
                },
                {
                    "haihongwangsong",
                    "海红网送"
                },
                {
                    "gongsuda",
                    "共速达"
                },
                {
                    "jialidatong",
                    "嘉里大通"
                },
                {
                    "ocs",
                    "OCS"
                },
                {
                    "usps",
                    "USPS"
                },
                {
                    "meiguokuaidi",
                    "美国快递"
                },
                {
                    "lijisong",
                    "立即送"
                },
                {
                    "yinjiesudi",
                    "银捷速递"
                },
                {
                    "menduimen",
                    "门对门"
                },
                {
                    "disifang",
                    "递四方"
                },
                {
                    "zhengzhoujianhua",
                    "郑州建华"
                },
                {
                    "hebeijianhua",
                    "河北建华"
                },
                {
                    "weitepai",
                    "微特派"
                },
                {
                    "dhlde",
                    "DHL-德国件"
                },
                {
                    "tonghetianxia",
                    "通和天下"
                },
                {
                    "emsguoji",
                    "EMS-国际件"
                },
                {
                    "fedexus",
                    "FedEx-美国件"
                },
                {
                    "fengxingtianxia",
                    "风行天下"
                },
                {
                    "kangliwuliu",
                    "康力物流"
                },
                {
                    "kuayue",
                    "跨越速递"
                },
                {
                    "haimengsudi",
                    "海盟速递"
                },
                {
                    "shenganwuliu",
                    "圣安物流"
                },
                {
                    "yitongfeihong",
                    "一统飞鸿"
                },
                {
                    "zhongsukuaidi",
                    "中速快递"
                },
                {
                    "neweggozzo",
                    "新蛋奥硕"
                },
                {
                    "ontrac",
                    "OnTrac"
                },
                {
                    "sevendays",
                    "七天连锁"
                },
                {
                    "mingliangwuliu",
                    "明亮物流"
                },
                {
                    "vancl",
                    "凡客配送"
                },
                {
                    "huaqikuaiyun",
                    "华企快运"
                },
                {
                    "city100",
                    "城市100"
                },
                {
                    "sxhongmajia",
                    "红马甲物流"
                },
                {
                    "suijiawuliu",
                    "穗佳物流"
                },
                {
                    "feibaokuaidi",
                    "飞豹快递"
                },
                {
                    "chuanxiwuliu",
                    "传喜物流"
                },
                {
                    "jietekuaidi",
                    "捷特快递"
                },
                {
                    "longlangkuaidi",
                    "隆浪快递"
                },
                {
                    "emsen",
                    "EMS-英文"
                },
                {
                    "zhongtianwanyun",
                    "中天万运"
                },
                {
                    "hkpost",
                    "香港(HongKong Post)"
                },
                {
                    "bangsongwuliu",
                    "邦送物流"
                },
                {
                    "guotongkuaidi",
                    "国通快递"
                },
                {
                    "auspost",
                    "澳大利亚(Australia Post)"
                },
                {
                    "canpost",
                    "加拿大邮政"
                },
                {
                    "canpostfr",
                    "加拿大邮政"
                },
                {
                    "upsen",
                    "UPS-全球件"
                },
                {
                    "tnten",
                    "TNT-全球件"
                },
                {
                    "dhlen",
                    "DHL-全球件"
                },
                {
                    "shunfengen",
                    "顺丰-美国件"
                },
                {
                    "huiqiangkuaidi",
                    "汇强快递"
                },
                {
                    "xiyoutekuaidi",
                    "希优特"
                },
                {
                    "haoshengwuliu",
                    "昊盛物流"
                },
                {
                    "shangcheng",
                    "尚橙物流"
                },
                {
                    "yilingsuyun",
                    "亿领速运"
                },
                {
                    "dayangwuliu",
                    "大洋物流"
                },
                {
                    "didasuyun",
                    "递达速运"
                },
                {
                    "yitongda",
                    "易通达"
                },
                {
                    "youbijia",
                    "邮必佳"
                },
                {
                    "yishunhang",
                    "亿顺航"
                },
                {
                    "feihukuaidi",
                    "飞狐快递"
                },
                {
                    "xiaoxiangchenbao",
                    "潇湘晨报"
                },
                {
                    "balunzhi",
                    "巴伦支"
                },
                {
                    "aramex",
                    "Aramex"
                },
                {
                    "minshengkuaidi",
                    "闽盛快递"
                },
                {
                    "syjiahuier",
                    "佳惠尔"
                },
                {
                    "minbangsudi",
                    "民邦速递"
                },
                {
                    "shanghaikuaitong",
                    "上海快通"
                },
                {
                    "xiaohongmao",
                    "北青小红帽"
                },
                {
                    "gsm",
                    "GSM"
                },
                {
                    "annengwuliu",
                    "安能物流"
                },
                {
                    "kcs",
                    "KCS"
                },
                {
                    "citylink",
                    "City-Link"
                },
                {
                    "diantongkuaidi",
                    "店通快递"
                },
                {
                    "fanyukuaidi",
                    "凡宇快递"
                },
                {
                    "pingandatengfei",
                    "平安达腾飞"
                },
                {
                    "guangdongtonglu",
                    "广东通路"
                },
                {
                    "zhongruisudi",
                    "中睿速递"
                },
                {
                    "kuaidawuliu",
                    "快达物流"
                },
                {
                    "jiajikuaidi",
                    "佳吉快递"
                },
                {
                    "adp",
                    "ADP国际快递"
                },
                {
                    "fardarww",
                    "颿达国际快递"
                },
                {
                    "fandaguoji",
                    "颿达国际快递(英文)"
                },
                {
                    "shlindao",
                    "林道国际快递"
                },
                {
                    "sinoex",
                    "中外运速递(中文)"
                },
                {
                    "zhongwaiyun",
                    "中外运速递"
                },
                {
                    "dechuangwuliu",
                    "深圳德创物流"
                },
                {
                    "ldxpres",
                    "林道国际快递(英文)"
                },
                {
                    "ruidianyouzheng",
                    "瑞典（Sweden Post）"
                },
                {
                    "postenab",
                    "Posten AB"
                },
                {
                    "nuoyaao",
                    "偌亚奥国际快递"
                },
                {
                    "chengjisudi",
                    "城际速递"
                },
                {
                    "xianglongyuntong",
                    "祥龙运通物流"
                },
                {
                    "pinsuxinda",
                    "品速心达快递"
                },
                {
                    "yuxinwuliu",
                    "宇鑫物流"
                },
                {
                    "peixingwuliu",
                    "陪行物流"
                },
                {
                    "hutongwuliu",
                    "户通物流"
                },
                {
                    "xianchengliansudi",
                    "西安城联速递"
                },
                {
                    "yujiawuliu",
                    "煜嘉物流"
                },
                {
                    "yiqiguojiwuliu",
                    "一柒国际物流"
                },
                {
                    "fedexcn",
                    "Fedex（国际件）中文"
                },
                {
                    "lianbangkuaidien",
                    "联邦快递-英文"
                },
                {
                    "zhongtongphone",
                    "中通（带电话）"
                },
                {
                    "saiaodimmb",
                    "赛澳递for买卖宝"
                },
                {
                    "shanghaiwujiangmmb",
                    "上海无疆for买卖宝"
                },
                {
                    "singpost",
                    "新加坡小包(Singapore Post)"
                },
                {
                    "yinsu",
                    "音素快运"
                },
                {
                    "ndwl",
                    "南方传媒物流"
                },
                {
                    "sucheng",
                    "速呈宅配"
                },
                {
                    "chuangyi",
                    "创一快递"
                },
                {
                    "dianyi",
                    "云南滇驿物流"
                },
                {
                    "cqxingcheng",
                    "重庆星程快递"
                },
                {
                    "scxingcheng",
                    "四川星程快递"
                },
                {
                    "gzxingcheng",
                    "贵州星程快递"
                },
                {
                    "ytkd",
                    "运通中港快递"
                },
                {
                    "gatien",
                    "Gati-英文"
                },
                {
                    "gaticn",
                    "Gati-中文"
                },
                {
                    "jcex",
                    "jcex官网通道"
                },
                {
                    "peex",
                    "派尔快递官网通道"
                },
                {
                    "kxda",
                    "凯信达官网通道"
                },
                {
                    "advancing",
                    "安达信官网通道"
                },
                {
                    "huiwen",
                    "汇文官网通道"
                },
                {
                    "yxexpress",
                    "亿翔官网通道"
                },
                {
                    "donghong",
                    "东红合作通道"
                },
                {
                    "feiyuanvipshop",
                    "飞远配送"
                },
                {
                    "hlyex",
                    "好运来"
                },
                {
                    "dpexen",
                    "Toll"
                },
                {
                    "zengyisudi",
                    "增益速递"
                },
                {
                    "kuaiyouda",
                    "四川快优达速递"
                },
                {
                    "riyuwuliu",
                    "日昱物流"
                },
                {
                    "sutongwuliu",
                    "速通物流"
                },
                {
                    "nanjingshengbang",
                    "南京晟邦物流"
                },
                {
                    "anposten",
                    "爱尔兰邮政(An Post)"
                },
                {
                    "japanposten",
                    "日本（Japan Post）"
                },
                {
                    "postdanmarken",
                    "丹麦邮政"
                },
                {
                    "brazilposten",
                    "巴西(Brazil Post/Correios)"
                },
                {
                    "postnlcn",
                    "荷兰挂号信(PostNL international registered mail)"
                },
                {
                    "postnl",
                    "荷兰挂号信(PostNL international registered mail)"
                },
                {
                    "emsukrainecn",
                    "乌克兰EMS-中文(EMS Ukraine)"
                },
                {
                    "emsukraine",
                    "EMS Ukraine"
                },
                {
                    "ukrpostcn",
                    "乌克兰邮政包裹"
                },
                {
                    "ukrpost",
                    "乌克兰小包、大包(UkrPost)"
                },
                {
                    "haihongmmb",
                    "海红for买卖宝"
                },
                {
                    "fedexuk",
                    "FedEx UK"
                },
                {
                    "fedexukcn",
                    "FedEx-英国件"
                },
                {
                    "dingdong",
                    "叮咚快递"
                },
                {
                    "dpd",
                    "DPD"
                },
                {
                    "upsfreight",
                    "UPS Freight"
                },
                {
                    "abf",
                    "ABF"
                },
                {
                    "purolator",
                    "Purolator"
                },
                {
                    "bpost",
                    "比利时（Bpost）"
                },
                {
                    "bpostinter",
                    "比利时国际(Bpost international)"
                },
                {
                    "lasership",
                    "LaserShip"
                },
                {
                    "parcelforce",
                    "英国大包、EMS（Parcel Force）"
                },
                {
                    "parcelforcecn",
                    "英国邮政大包EMS"
                },
                {
                    "yodel",
                    "YODEL"
                },
                {
                    "dhlnetherlands",
                    "DHL-荷兰（DHL Netherlands）"
                },
                {
                    "myhermes",
                    "MyHermes"
                },
                {
                    "dpdgermany",
                    "DPD Germany"
                },
                {
                    "fastway",
                    "Fastway Ireland"
                },
                {
                    "chronopostfra",
                    "法国(大包、EMS)-法文（Chronopost France）"
                },
                {
                    "selektvracht",
                    "Selektvracht"
                },
                {
                    "lanhukuaidi",
                    "蓝弧快递"
                },
                {
                    "belgiumpost",
                    "比利时(Belgium Post)"
                },
                {
                    "upsmailinno",
                    "UPS Mail Innovations"
                },
                {
                    "postennorge",
                    "挪威（Posten Norge）"
                },
                {
                    "swisspostcn",
                    "瑞士邮政"
                },
                {
                    "swisspost",
                    "瑞士(Swiss Post)"
                },
                {
                    "royalmailcn",
                    "英国邮政小包"
                },
                {
                    "royalmail",
                    "英国小包（Royal Mail）"
                },
                {
                    "dhlbenelux",
                    "DHL Benelux"
                },
                {
                    "novaposhta",
                    "Nova Poshta"
                },
                {
                    "dhlpoland",
                    "DHL-波兰（DHL Poland）"
                },
                {
                    "estes",
                    "Estes"
                },
                {
                    "tntuk",
                    "TNT UK"
                },
                {
                    "deltec",
                    "Deltec Courier"
                },
                {
                    "opek",
                    "OPEK"
                },
                {
                    "dpdpoland",
                    "DPD Poland"
                },
                {
                    "italysad",
                    "Italy SDA"
                },
                {
                    "mrw",
                    "MRW"
                },
                {
                    "chronopostport",
                    "Chronopost Portugal"
                },
                {
                    "correosdees",
                    "西班牙(Correos de Espa\x00f1a)"
                },
                {
                    "directlink",
                    "Direct Link"
                },
                {
                    "eltahell",
                    "ELTA Hellenic Post"
                },
                {
                    "ceskaposta",
                    "捷克（Česk\x00e1 pošta）"
                },
                {
                    "siodemka",
                    "Siodemka"
                },
                {
                    "seur",
                    "International Seur"
                },
                {
                    "jiuyicn",
                    "久易快递"
                },
                {
                    "hrvatska",
                    "克罗地亚（Hrvatska Posta）"
                },
                {
                    "bulgarian",
                    "保加利亚（Bulgarian Posts）"
                },
                {
                    "portugalseur",
                    "Portugal Seur"
                },
                {
                    "ecfirstclass",
                    "EC-Firstclass"
                },
                {
                    "dtdcindia",
                    "DTDC India"
                },
                {
                    "safexpress",
                    "Safexpress"
                },
                {
                    "koreapost",
                    "韩国（Korea Post）"
                },
                {
                    "tntau",
                    "TNT Australia"
                },
                {
                    "thailand",
                    "泰国（Thailand Thai Post）"
                },
                {
                    "skynetmalaysia",
                    "SkyNet Malaysia"
                },
                {
                    "malaysiapost",
                    "马来西亚小包（Malaysia Post(Registered)）"
                },
                {
                    "malaysiaems",
                    "马来西亚大包、EMS（Malaysia Post(parcel,EMS)）"
                },
                {
                    "jd",
                    "京东"
                },
                {
                    "saudipost",
                    "沙特阿拉伯(Saudi Post)"
                },
                {
                    "southafrican",
                    "南非（South African Post Office）"
                },
                {
                    "ocaargen",
                    "OCA Argentina"
                },
                {
                    "nigerianpost",
                    "尼日利亚(Nigerian Postal)"
                },
                {
                    "chile",
                    "智利(Correos Chile)"
                },
                {
                    "israelpost",
                    "以色列(Israel Post)"
                },
                {
                    "tollpriority",
                    "Toll Priority(Toll Online)"
                },
                {
                    "estafeta",
                    "Estafeta"
                },
                {
                    "gdkd",
                    "港快速递"
                },
                {
                    "mexico",
                    "墨西哥（Correos de Mexico）"
                },
                {
                    "romanian",
                    "罗马尼亚（Posta Romanian）"
                },
                {
                    "tntitaly",
                    "TNT Italy"
                },
                {
                    "multipack",
                    "Mexico Multipack"
                },
                {
                    "portugalctt",
                    "葡萄牙（Portugal CTT）"
                },
                {
                    "interlink",
                    "Interlink Express"
                },
                {
                    "dpduk",
                    "DPD UK"
                },
                {
                    "hzpl",
                    "华航快递"
                },
                {
                    "gatikwe",
                    "Gati-KWE"
                },
                {
                    "redexpress",
                    "Red Express"
                },
                {
                    "mexicodenda",
                    "Mexico Senda Express"
                },
                {
                    "tcixps",
                    "TCI XPS"
                },
                {
                    "hre",
                    "高铁速递"
                },
                {
                    "speedpost",
                    "新加坡EMS、大包(Singapore Speedpost)"
                },
                {
                    "emsinten",
                    "EMS国际（英文）"
                },
                {
                    "asendiausa",
                    "Asendia USA"
                },
                {
                    "chronopostfren",
                    "法国（大包、EMS）-英文(Chronopost France)"
                },
                {
                    "italiane",
                    "意大利(Poste Italiane)"
                },
                {
                    "gda",
                    "冠达快递"
                },
                {
                    "chukou1",
                    "出口易"
                },
                {
                    "huangmajia",
                    "黄马甲"
                },
                {
                    "anlexpress",
                    "新干线快递"
                },
                {
                    "shipgce",
                    "飞洋快递"
                },
                {
                    "xlobo",
                    "贝海国际速递"
                },
                {
                    "emirates",
                    "阿联酋(Emirates Post)"
                },
                {
                    "nsf",
                    "新顺丰（NSF）"
                },
                {
                    "pakistan",
                    "巴基斯坦(Pakistan Post)"
                },
                {
                    "shiyunkuaidi",
                    "世运快递"
                },
                {
                    "ucs",
                    "合众速递(UCS）"
                },
                {
                    "afghan",
                    "阿富汗(Afghan Post)"
                },
                {
                    "belpost",
                    "白俄罗斯(Belpochta)"
                },
                {
                    "quantwl",
                    "全通快运"
                },
                {
                    "zhaijibian",
                    "宅急便"
                },
                {
                    "efs",
                    "EFS Post"
                },
                {
                    "tntpostcn",
                    "TNT Post"
                },
                {
                    "gml",
                    "英脉物流"
                },
                {
                    "gtongsudi",
                    "广通速递"
                },
                {
                    "donghanwl",
                    "东瀚物流"
                },
                {
                    "rpx",
                    "rpx"
                },
                {
                    "rrs",
                    "日日顺物流"
                },
                {
                    "yamato",
                    "黑猫雅玛多"
                },
                {
                    "htongexpress",
                    "华通快运"
                },
                {
                    "kyrgyzpost",
                    "吉尔吉斯斯坦(Kyrgyz Post)"
                },
                {
                    "latvia",
                    "拉脱维亚(Latvijas Pasts)"
                },
                {
                    "libanpost",
                    "黎巴嫩(Liban Post)"
                },
                {
                    "lithuania",
                    "立陶宛（Lietuvos paštas）"
                },
                {
                    "maldives",
                    "马尔代夫(Maldives Post)"
                },
                {
                    "malta",
                    "马耳他（Malta Post）"
                },
                {
                    "macedonia",
                    "马其顿(Macedonian Post)"
                },
                {
                    "newzealand",
                    "新西兰（New Zealand Post）"
                },
                {
                    "moldova",
                    "摩尔多瓦"
                },
                {
                    "bangladesh",
                    "孟加拉国(EMS)"
                },
                {
                    "serbia",
                    "塞尔维亚(PE Post of Serbia)"
                },
                {
                    "cypruspost",
                    "塞浦路斯"
                },
                {
                    "tunisia",
                    "突尼斯(EMS)"
                },
                {
                    "uzbekistan",
                    "乌兹别克斯坦"
                },
                {
                    "caledonia",
                    "新喀里多尼亚[法国]"
                },
                {
                    "republic",
                    "叙利亚"
                },
                {
                    "haypost",
                    "亚美尼亚"
                },
                {
                    "yemen",
                    "也门"
                },
                {
                    "india",
                    "印度(India Post)"
                },
                {
                    "england",
                    "英国(大包,EMS)"
                },
                {
                    "jordan",
                    "约旦"
                },
                {
                    "vietnam",
                    "越南小包(Vietnam Posts)"
                },
                {
                    "montenegro",
                    "黑山(Pošta Crne Gore)"
                },
                {
                    "correos",
                    "哥斯达黎加"
                },
                {
                    "xilaikd",
                    "西安喜来快递"
                },
                {
                    "hanrun",
                    "韩润物流"
                },
                {
                    "greenland",
                    "格陵兰[丹麦]（TELE Greenland A/S）"
                },
                {
                    "phlpost",
                    "菲律宾（Philippine Postal）"
                },
                {
                    "ecuador",
                    "厄瓜多尔(Correos del Ecuador)"
                },
                {
                    "iceland",
                    "冰岛(Iceland Post)"
                },
                {
                    "emonitoring",
                    "波兰小包(Poczta Polska)"
                },
                {
                    "albania",
                    "阿尔巴尼亚(Posta shqipatre)"
                },
                {
                    "aruba",
                    "阿鲁巴[荷兰]（Post Aruba）"
                },
                {
                    "egypt",
                    "埃及（Egypt Post）"
                },
                {
                    "ireland",
                    "爱尔兰(An Post)"
                },
                {
                    "omniva",
                    "爱沙尼亚(Eesti Post)"
                },
                {
                    "leopard",
                    "云豹国际货运"
                },
                {
                    "sinoairinex",
                    "中外运空运"
                },
                {
                    "hyk",
                    "上海昊宏国际货物"
                },
                {
                    "ckeex",
                    "城晓国际快递"
                },
                {
                    "hungary",
                    "匈牙利（Magyar Posta）"
                },
                {
                    "macao",
                    "澳门(Macau Post)"
                },
                {
                    "postserv",
                    "台湾（中华邮政）"
                },
                {
                    "bjemstckj",
                    "北京EMS"
                },
                {
                    "correoargentino",
                    "阿根廷(Correo Argentino)"
                },
                {
                    "kuaitao",
                    "快淘快递"
                },
                {
                    "peru",
                    "秘鲁(SERPOST)"
                },
                {
                    "indonesia",
                    "印度尼西亚EMS(Pos Indonesia-EMS)"
                },
                {
                    "kazpost",
                    "哈萨克斯坦(Kazpost)"
                },
                {
                    "lbbk",
                    "立白宝凯物流"
                },
                {
                    "bqcwl",
                    "百千诚物流"
                },
                {
                    "pfcexpress",
                    "皇家物流"
                },
                {
                    "csuivi",
                    "法国小包(Colissimo)"
                },
                {
                    "austria",
                    "奥地利(Austrian Post)"
                },
                {
                    "ukraine",
                    "乌克兰小包、大包(UkrPoshta)"
                },
                {
                    "uganda",
                    "乌干达(Posta Uganda)"
                },
                {
                    "azerbaijan",
                    "阿塞拜疆EMS(EMS AzerExpressPost)"
                },
                {
                    "finland",
                    "芬兰(Itella Posti Oy)"
                },
                {
                    "slovak",
                    "斯洛伐克(Slovensk\x00e1 Posta)"
                },
                {
                    "ethiopia",
                    "埃塞俄比亚(Ethiopian postal)"
                },
                {
                    "luxembourg",
                    "卢森堡(Luxembourg Post)"
                },
                {
                    "mauritius",
                    "毛里求斯(Mauritius Post)"
                },
                {
                    "brunei",
                    "文莱(Brunei Postal)"
                },
                {
                    "quantium",
                    "Quantium"
                },
                {
                    "tanzania",
                    "坦桑尼亚"
                },
                {
                    "oman",
                    "阿曼(Oman Post)"
                },
                {
                    "gibraltar",
                    "直布罗陀[英国]"
                },
                {
                    "byht",
                    "博源恒通"
                },
                {
                    "vnpost",
                    "越南EMS"
                },
                {
                    "anxl",
                    "安迅物流"
                },
                {
                    "dfpost",
                    "达方物流"
                },
                {
                    "huoban",
                    "伙伴物流"
                },
                {
                    "tianzong",
                    "天纵物流"
                },
                {
                    "bohei",
                    "波黑(JP BH Posta)"
                },
                {
                    "bolivia",
                    "玻利维亚"
                },
                {
                    "cambodia",
                    "柬埔寨"
                },
                {
                    "bahrain",
                    "巴林(Bahrain Post)"
                },
                {
                    "namibia",
                    "纳米比亚"
                },
                {
                    "rwanda",
                    "卢旺达"
                },
                {
                    "lesotho",
                    "莱索托"
                },
                {
                    "kenya",
                    "肯尼亚"
                },
                {
                    "cameroon",
                    "喀麦隆"
                },
                {
                    "belize",
                    "伯利兹"
                },
                {
                    "paraguay",
                    "巴拉圭(Correo Paraguayo)"
                },
                {
                    "sfift",
                    "十方通物流"
                },
                {
                    "hnfy",
                    "飞鹰物流"
                },
                {
                    "iparcel",
                    "i-pacle"
                },
                {
                    "bjxsrd",
                    "鑫锐达"
                },
                {
                    "baishiwuliu",
                    "百世物流"
                }
            };
        }
    }
}
